settings=
{
    ["osb_buttons"]=
    {
        [11]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=8,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="MSG",
            ["source_osb"]=16,
        },
        [13]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=3,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="STAT",
            ["source_osb"]=6,
        },
        [12]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=10,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="CDU",
            ["source_osb"]=15,
        },
        [14]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=6,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="TGP",
            ["source_osb"]=18,
        },
    },
}
