settings=
{
    ["osb_buttons"]=
    {
        [11]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=4,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="MAV",
            ["source_osb"]=8,
        },
        [13]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=5,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="DSMS",
            ["source_osb"]=17,
        },
        [12]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=1,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="LOAD",
            ["source_osb"]=7,
        },
        [14]=
        {
            ["target_mode"]=
            {
                ["level_3"]=0,
                ["master"]=7,
                ["level_4"]=0,
                ["level_2"]=0,
            },
            ["label"]="TAD",
            ["source_osb"]=19,
        },
    },
}
